### ISSUE TITLE
Use `require` instead of `assert` in go unit test, to conform with the server repo and other plugin repos

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-starter-template#103]

**Comment by hanzei** [comment]
@mickmister Could you elaborate a bit why this changes is needed? `mattermost-server` uses both `assert` and `require` and that seams to me a reasonable, as both packages cover different use cases.

**Comment by mickmister** [comment]
@hanzei it's not necessary. I was thinking of when we got rid of t.Fatal calls in favor of require logic equivalents. Assert is fine, I just haven't used it in a plugin project before as far as I know
