### ISSUE TITLE
Build fails when removing the webapp component

### ISSUE THREAD

**Issue by Salatfreak** [mattermost/mattermost-plugin-starter-template#112]
According to the [README](/mattermost/mattermost-plugin-starter-template/blob/master/README.md#how-do-i-make-a-server-only-or-web-app-only-plugin) we can simply delete the `webapp` folders and remove the corresponding sections from `plugin.json`. `make` will produce the following error message though:

> make: *** No rule to make target 'webapp/package.json', needed by 'webapp/node_modules'.  Stop.

This could for example be fixed by always fulfiling the `webapp/package.json` target if the plugin doesn't have a webapp like so:
```make
## Always fulfil webapp/package.json if plugin doesn't have webapp
ifeq ($(HAS_WEBAPP),)
.PHONY: webapp/package.json
webapp/package.json: ;
endif
```

**Comment by hanzei** [comment]
Good catch @Salatfreak. Are you intested in submitting a patch for this bug?
