### ISSUE TITLE
Trailing slash on `MM_SERVICESETTINGS_SITEURL` causes non-obvious errors

### ISSUE THREAD

**Issue by shieldsjared** [mattermost/mattermost-plugin-starter-template#115]
While attempting to use this starter template, I set my `MM_SERVICESETTINGS_SITEURL` with a trailing slash.  It was not immediately obvious that this was the cause of the error I was receiving, as it _appeared_ that some calls were successful while others were not

```
2020/08/21 13:00:02 Authenticating using token against https://mattermost/.
2020/08/21 13:00:02 Uploading plugin via API.
2020/08/21 13:00:02 Enabling plugin.
Failed: failed to enable plugin: : Sorry, we could not find the page., There doesn't appear to be an api call for the url='/api/v4/plugins/resfor-mattermost-azure-devops-integration/enable'.  Typo? are you missing a team_id or user_id as part of the url?

Usage:
    pluginctl deploy <plugin id> <bundle path>
    pluginctl disable <plugin id>
    pluginctl enable <plugin id>
    pluginctl reset <plugin id>
make: *** [Makefile:127: deploy] Error 1
```

As you can see in the log, the upload _appears_ to work, but then the subsequent call to enable it fails. What's interesting is that I dug into the logs and found that the upload actually did not succeed at all... This led to quite a bit of chin scratching and hunting through code before realizing I should remove the trailing slash.

Not sure if the best solution is to
1. Trim the trailing slash for the end-user, or
2. Put a comment in the readme file (easiest)

Happy to submit a PR for either.

**Comment by hanzei** [comment]
Trimming the trailing slash is a fine solution. Looking forward to your PR! :+1:

**Comment by shieldsjared** [comment]
@hanzei - PR Submitted.
