### ISSUE TITLE
Suggestion: make the template more 'marketplace-ready'

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-plugin-starter-template#132]
It would be useful if plugins based on this template were to achieve the basic marketplace requirements automatically: less effort both for plugin maintainers (no need to hunt out missing requirements in the docs) and for the marketplace reviewers (more requirements would be already checked).

This could be achieved by:
1. Completing the plugin.json file with the required fields:
```json
"homepage_url": "https://github.com/mattermost/mattermost-plugin-starter-template/",
"support_url": "https://mattermost/mattermost-plugin-starter-template/issues",
"release_notes_url": "https://mattermost/mattermost-plugin-starter-template/releases/tag/vX.X.X",
"icon_path": "assets/starter-template-icon.svg"
```
+ adding the SVG file in /assets

2. Make a README.md.template file that would be used for the real plugin (a distinct file might make it easier to differentiate  template-only instructions from what is expected for a plugin's README):
- add a "maintainer" section
- add a "usage" section
- add a "feedback" section
- add a "Configuration Notes in HA" section
- add a "compatibility" section (not a marketplace requirement but with the plugin API fast changes, users of older mattermost server versions can have trouble finding the right plugin version) 

3. Udpate the current README to take these changes into account

**Comment by hanzei** [comment]
These are all great suggestions :+1: https://github.com/mattermost/mattermost-plugin-demo/blob/master/assets/icon.svg might be a good icon to use as default.
