### ISSUE TITLE
Error after running `make`

### ISSUE THREAD

**Issue by gleke** [mattermost/mattermost-plugin-starter-template#140]
```
gleke@gleke-QTJ5: ~$ git clone --depth 1 https://github.com/mattermost/mattermost-plugin-starter-template com.example.my-plugin

gleke@gleke-QTJ5:~$ cd com.example.my-plugin
gleke@gleke-QTJ5:~$ make

> @ check-types /home/gleke/com.example.my-plugin/webapp
> tsc

Running golangci-lint
golangci-lint run ./...
ERRO Running error: context loading failed: no go files to analyze 
Makefile:43: recipe for target 'check-style' failed
make: *** [check-style] Error 5
gleke@gleke-QTJ5:~/com.example.my-plugin$ 

```

**Comment by hanzei** [comment]
What version of `golangci-lint` are you running?

**Comment by gleke** [comment]
golangci-lint has version 1.33.0 built from b90551c on 2020-11-23T05:15:36Z

**Comment by hanzei** [comment]
Hm, I can't reproduce the issue on my local server. But I found a similar issue on the golangci-lint repo: https://github.com/golangci/golangci-lint/issues/825. Does one of the tips like https://github.com/golangci/golangci-lint/issues/825#issuecomment-666038142 help you?

**Comment by hanzei** [comment]
Closing as a stale ticket
