### ISSUE TITLE
Template installation issue: make freezes during npm install

### ISSUE THREAD

**Issue by girish17** [mattermost/mattermost-plugin-starter-template#142]
`make` operation freezes during `npm install`. Freezes at `extract:@icons/material: sill extract @icons/material@0.2.4 extracted`

**Comment by hanzei** [comment]
Could you please run `make clean` and then `make`?

**Comment by girish17** [comment]
Tried that.
![frozenMake](https://user-images.githubusercontent.com/25923137/102178686-dce1c980-3ecb-11eb-9699-b5e08e429266.png)
Doesn't seem to work. Is the [Getting Started](https://github.com/mattermost/mattermost-plugin-starter-template#getting-started) section up to date?

**Comment by hanzei** [comment]
What OS and `npm` version are you using? Just tested locally on a Linux system with `6.14.8` and didn't found any issues.

**Comment by girish17** [comment]
OS - `Ubuntu 20.04 LTS GNU/Linux 64 bit`
Kernel - `Linux 5.4.0-58-generic x86_64`
NPM version - `6.14.4`

**Comment by girish17** [comment]
Tried again from scratch, installed few missing dependencies and it works now! Thanks @hanzei

**Comment by girish17** [comment]
On a side note - This template still freezes during `make` with following configuration:
OS - `Trisquel 8 Fildas GNU/Linux 64 bit` (based on Ubuntu 16.04 LTS)
Kernel - `4.4.0-197-generic #229+8.0trisquel3`
NPM version - `6.14.8`

Seems, like this is an unusual bug related to some dependency and the only fix I could think of is to stick to a config that worked (as mentioned earlier).
