### ISSUE TITLE
go.mod has incorrect Golang version

### ISSUE THREAD

**Issue by icelander** [mattermost/mattermost-plugin-starter-template#146]
**Steps to reproduce**

1. Install Golang v1.12.x
2. Clone this repository & `cd` into it
3. run `make dist`

**Expected Behavior**

Example plugin builds successfully

**Observed Behavior**

Plugin fails to build. Output indicates the version of `go-multierror` required needs Golang v1.14+:

```
# github.com/hashicorp/go-multierror
../../../go/pkg/mod/github.com/hashicorp/go-multierror@v1.1.0/multierror.go:112:9: undefined: errors.As
../../../go/pkg/mod/github.com/hashicorp/go-multierror@v1.1.0/multierror.go:117:9: undefined: errors.Is
note: module requires Go 1.14
# github.com/hashicorp/go-multierror
../../../go/pkg/mod/github.com/hashicorp/go-multierror@v1.1.0/multierror.go:112:9: undefined: errors.As
../../../go/pkg/mod/github.com/hashicorp/go-multierror@v1.1.0/multierror.go:117:9: undefined: errors.Is
note: module requires Go 1.14
make: build/bin/manifest: Command not found
build/setup.mk:16: *** "Cannot parse id from plugin.json".  Stop.
```

**Comment by hanzei** [comment]
This will be fixed with https://github.com/mattermost/mattermost-plugin-starter-template/pull/145 as go 1.16. is required then.

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-starter-template/pull/145
