### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by girish17** [mattermost/mattermost-plugin-starter-template#148]
Running golangci-lint
golangci-lint run ./...
server/plugin.go:12:13: fieldalignment: struct with 64 pointer bytes could be 40 (govet)
type Plugin struct {
            ^
make: *** [Makefile:48: check-style] Error 1

**Comment by hanzei** [comment]
What version of `golangci-lint` do you have installed?

**Comment by girish17** [comment]
golangci-lint has version 1.39.0 built from 9aea4aee on 2021-03-26T08:02:53Z

**Comment by girish17** [comment]
After checking out code from `148_fieldalignment` branch and running `make` command, no errors were found. The plugin was built successfully and `make deploy` worked.
