### ISSUE TITLE
Potential server version requirement discrepancy

### ISSUE THREAD

**Issue by moussetc** [mattermost/mattermost-plugin-starter-template#172]
The server Go code is compiled using [mattermost-server/v6 ](https://github.com/mattermost/mattermost-plugin-starter-template/blob/59b65969364f555a6f9987b59d0da78dd6109084/go.mod#L6)has dependency, but the plugin.json [only requires a minimum server version of 5.37](https://github.com/mattermost/mattermost-plugin-starter-template/blob/59b65969364f555a6f9987b59d0da78dd6109084/plugin.json#L10).

Should it be the same version in both files?

**Comment by hanzei** [comment]
Jep, the min server version should be bumped.
