### ISSUE TITLE
Basic plugin builds artifacts larger than 50MB, the common max upload size on default Mattermost setups 

### ISSUE THREAD

**Issue by sadohert** [mattermost/mattermost-plugin-starter-template#194]
I was using this template to start a new plugin.

I followed the instructions but ran into an issue when I went to test the bare minimum plugin with `make deploy` using [`mattermost-preview`](https://docs.mattermost.com/install/common-local-deploy-docker.html) docker image.

I was initially getting the following error:

```
2023/12/27 22:42:36 Uploading plugin via API.
Failed: failed to upload plugin bundle: AppErrorFromJSON: model.utils.decode_json.app_error, body: http: request body too large
, invalid character 'h' looking for beginning of value

Usage:
    pluginctl deploy <plugin id> <bundle path>
    pluginctl disable <plugin id>
    pluginctl enable <plugin id>
    pluginctl reset <plugin id>
make: *** [deploy] Error 1
```

I found [a thread](https://community.mattermost.com/core/pl/qenhx7gz4fny9ke4kpk7ojb33o) on the COmmunity server that pointed out that I needed to increase the max file upload size under "System Console > File Storage > Max Upload Filesize".  I checked on the size of the bare bones plugin archive and it was around 53MB.

Can we somehow provide  warning text in the `make deploy` target to explain this possible issue to developers?

**Comment by hanzei** [comment]
Good catch. The error could surely be clearer. Opened https://mattermost.atlassian.net/browse/MM-56455.
