### ISSUE TITLE
Missing go get on fresh install

### ISSUE THREAD

**Issue by manland** [mattermost/mattermost-plugin-starter-template#42]
I have installed a fresh dev env (go). When i clone this repo and start `make` it fail with errors.

Missing dep are :

* github.com/mattermost/mattermost-server/model
* github.com/pkg/errors

I need to `go get` them manually.

I see 2 options : 

* add step in readme
* add go get in make file

**Comment by hanzei** [comment]
Both of the packages are part of `go.mod`. See
- https://github.com/mattermost/mattermost-plugin-sample/blob/master/go.mod#L14
- https://github.com/mattermost/mattermost-plugin-sample/blob/master/go.mod#L20

What is the error that occurs?

**Comment by manland** [comment]
```
git:(init-mattermost-plugin) ✗ make main.go:9:2: cannot find package "github.com/mattermost/mattermost-server/model" in any of: /home/xxx/soft/go/src/github.com/mattermost/mattermost-server/model (from $GOROOT) /home/xxx/dev/go/src/github.com/mattermost/mattermost-server/model (from $GOPATH) main.go:10:2: cannot find package "github.com/pkg/errors" in any of: /home/xxx/soft/go/src/github.com/pkg/errors (from $GOROOT) /home/xxx/dev/go/src/github.com/pkg/errors (from $GOPATH) make: build/bin/manifest: Command not found
```

after go get 2 dep all is ok

**Comment by hanzei** [comment]
Would you please try if running `export GO111MODULE=on` before  `make` fixes this issue?

**Comment by ThiefMaster** [comment]
I had the same issue and the export worked for me.

**Comment by hanzei** [comment]
@ThiefMaster @manland You should clone the repository to a directory outside of `$GOPATH`. This should be the "clean" way to fix this. If the repository is inside of `$GOPATH`, you have to run `export GO111MODULE=on` before the first build.

**Comment by lieut-data** [comment]
Go modules is still pretty new, and I know others have run into this point of confusion before. I've proposed a tweak to README.md that should clarify this: https://github.com/mattermost/mattermost-plugin-sample/pull/44.

**Comment by manland** [comment]
Thanks!

**Comment by lieut-data** [comment]
Thanks, @manland! Considering this resolved as of https://github.com/mattermost/mattermost-plugin-starter-template/pull/44.

**Comment by s-trooper** [comment]
i got the same error, my $GOPATH is empty and "export GO111MODULE=on" doesnt help. I have no idea of golang/enviromant. can anyone help me please?
```
main.go:9:2: cannot find package "github.com/mattermost/mattermost-server/v5/model" in any of:
        /usr/lib/go-1.10/src/github.com/mattermost/mattermost-server/v5/model (from $GOROOT)
        /home/xxx/go/src/github.com/mattermost/mattermost-server/v5/model (from $GOPATH)
main.go:10:2: cannot find package "github.com/pkg/errors" in any of:
        /usr/lib/go-1.10/src/github.com/pkg/errors (from $GOROOT)
        /home/xxx/go/src/github.com/pkg/errors (from $GOPATH)
main.go:11:2: cannot find package "github.com/mattermost/mattermost-server/v5/model" in any of:
        /usr/lib/go-1.10/src/github.com/mattermost/mattermost-server/v5/model (from $GOROOT)
        /home/xxx/go/src/github.com/mattermost/mattermost-server/v5/model (from $GOPATH)
main.go:12:2: cannot find package "github.com/mholt/archiver/v3" in any of:
        /usr/lib/go-1.10/src/github.com/mholt/archiver/v3 (from $GOROOT)
        /home/xxx/go/src/github.com/mholt/archiver/v3 (from $GOPATH)
main.go:13:2: cannot find package "github.com/pkg/errors" in any of:
        /usr/lib/go-1.10/src/github.com/pkg/errors (from $GOROOT)
        /home/xxx/go/src/github.com/pkg/errors (from $GOPATH)
make: build/bin/manifest: Command not found
build/setup.mk:16: *** "Cannot parse id from plugin.json".  Stop.
```

**Comment by lieut-data** [comment]
@agarciamontoro, I know you recently ran into some pain re: `$GOPATH`. Does this look similar to your issue? Any suggestions for @s-trooper or how we can improve things here?

**Comment by s-trooper** [comment]
@lieut-data i got this solved, it compiles with go1.15 but not go1.10 for me. next error that comes after can be solved with lates nodejs :)

**Comment by agarciamontoro** [comment]
Great that you solved this, @s-trooper! Let us know if you have any other issues.

For the record, and although I don't think this was the problem here, if anyone has problems with an empty `$GOPATH`, it does not hurt to do `export GOPATH=$(go env GOPATH)` to make sure that the OS variable is set even if `GOPATH` is not explicitly set (which defaults to `$HOME/go`)
