### ISSUE TITLE
golang module error (Mac)

### ISSUE THREAD

**Issue by shintaro-hz** [mattermost/mattermost-plugin-starter-template#65]
I have got some errors as shown bellow when I did make command.
Mac OS 10.14.6
go version go1.13 darwin/amd64

Could you tell me how to fix it...

`go: github.com/mattermost/mattermost-server@v5.12.0+incompatible requires
	willnorris.com/go/imageproxy@v0.8.1-0.20190326225038-d4246a08fdec requires
	cloud.google.com/go@v0.37.1 requires
	go.opencensus.io@v0.19.1 requires
	google.golang.org/genproto@v0.0.0-20181219182458-5a97ab628bfb requires
	google.golang.org/grpc@v1.16.0 requires
	github.com/golang/lint@v0.0.0-20190227174305-8f45f776aaf1: invalid pseudo-version: does not match version-control timestamp (2018-12-17T17:45:47Z)
make: build/bin/manifest: Command not found
build/setup.mk:13: *** "Cannot parse id from plugin.json".  Stop.`

**Comment by hanzei** [comment]
This looks like a problem with go1.13. We didn't got around updating our tool chain to go 1.13, but I will take care of this.

**Comment by shintaro-hz** [comment]
Thank you for reply.

I will downgrade Go version.
Which version is stable to build mattermost app?

**Comment by hanzei** [comment]
You should use at least `go1.12.3`

**Comment by hanzei** [comment]
Hey @shintaro-hz,

I tried to repo your problem, but wasn't able. I'm using `go version go1.13 linux/amd64`. Would you please try and run `make clean` before your build?

**Comment by aaronrothschild** [comment]
@shintaro-hz I'm assuming this issue has been resolved.  Closing, please log a new issue if it's still occurring.
