### ISSUE TITLE
Investigate stripping symbol table and debugging information

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-plugin-starter-template#68]
Building https://github.com/mattermost/mattermost-plugin-autolink with `-ldflags="-s -w"` reduces the final bundle down from `26M` to `16M`. Other plugins would benefit similarly.

As per http://dominik.honnef.co/posts/2016/10/go-and-strip/,
> In addition to the misconception that stripping Go binaries breaks them, there have been several related misconceptions. The biggest one is that strip would make panic stacktraces useless by stripping function names, file names and line numbers. This is not the case. While strip will remove various useful debug information, it will not affect how panics are rendered. This also implies that strip is not sufficient to guarantee that all identifying information are removed from an executable.

Investigate the impact of the `ldflags` addition above, compare it to `strip`, and make a `Makefile` recommendation that distinguishes production from development builds, preserving debugging symbols in the later.

**Comment by hanzei** [comment]
FYI: I've brought this topic up before (https://community.mattermost.com/core/pl/q1wgghckfbfemmaw55z1o67ewh).

@lieut-data What do you think about making this a Help Wanted?

**Comment by lieut-data** [comment]
@hanzei, I'm open to that. In fact, I think that's what I meant to do when opening this ticket, but found we hadn't synced the labels to this repository, and then got sidetracked. Is it possible to sync the labels here as such?

cc @crspeller re: the description above, since you specifically raised concerns about stripping debugging symbols before.

**Comment by crspeller** [comment]
Ya. I would be against this. The cost of additional issues debugging is not worth the minor reduction is file size. 
Imagine if we stripped the server in production and Shift was having a perf issue. I imagine the profiler doesn't work very well with a stripped binary.

**Comment by lieut-data** [comment]
@crspeller, that's fair. We don't really have any infrastructure to profile plugins right now, but imagining that did exist, would it be an enterprise-only feature?

Even then, there's probably benefit to reducing the number of "things we have to test". So if we keep plugins with debugging symbols, there's probably no reason to add the QA burden of testing the ones without.

Closing as discussed.
