### ISSUE TITLE
Fix `make deploy` to correctly report an error

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-plugin-starter-template#69]
Running `make deploy` can appear to succeed:

```
> make deploy
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   735  100   679  100    56   7216    595 --:--:-- --:--:-- --:--:--  7223
Installing plugin via API
OK.
```

when in fact the configured `MM_ADMIN_USERNAME` or `MM_ADMIN_PASSWORD` was rejected by the server:
```
DEBU[2019-11-01T15:15:56.513026-04:00] Received HTTP request                         caller="web/handlers.go:77" method=POST request_id=97xj8ku85i81u89mq3oudjxf9c url=/api/v4/plugins/com.mattermost.webex/
enable
DEBU[2019-11-01T15:15:56.5131168-04:00] Invalid or expired session, please login again.  caller="mlog/log.go:162" err_details=UserRequired err_where= http_code=401 ip_addr="::1" method=POST path=/api/v4/p
lugins/com.mattermost.plugin-starter-template/enable request_id=97xj8ku85i81u89mq3oudjxf9c user_id=
```

The issue is that a login failure doesn't propagate outside of the attempt to capture the resulting token:
https://github.com/mattermost/mattermost-plugin-starter-template/blob/69b6ae8467fc7e80d7f128556e28de292fc289ab/Makefile#L148

Find a way to continue capturing the token but detect a login error (or any other upload issue), and ideally without using temporary files.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by nathanmkaya** [comment]
Hey @lieut-data can I have a go at this?

**Comment by hanzei** [comment]
Sure, thanks @nathanmkaya :+1:
