### ISSUE TITLE
golangci-lint version 1.25.1 causes error in build/manifest/main.go

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-plugin-starter-template#95]
@jfrerich Would you please report the gosec issue on https://github.com/mattermost/mattermost-plugin-starter-template?

_Originally posted by @hanzei in https://github.com/mattermost/mattermost-plugin-demo/pull/100#issuecomment-622308714_

### Summary
This issue was found after integrating golangci-lint into the mattermost-plugin-demo repo (https://github.com/mattermost/mattermost-plugin-demo/pull/100).  

If running v1.25.1 the following *gosec* error shows up.  This issue needs a resolution (still to be determined).

![image](https://user-images.githubusercontent.com/7575921/80821611-afdfe100-8b9e-11ea-8a2e-9994d8db93db.png)

**Comment by hanzei** [comment]
This was fixed by https://github.com/mattermost/mattermost-plugin-starter-template/pull/96. Closing.
